# Generated by Django 5.1.4 on 2024-12-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='店舗')),
                ('address', models.CharField(max_length=50, verbose_name='住所')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='緯度')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
            },
        ),
    ]
