# Generated by Django 5.1.4 on 2024-12-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='NEWタグ'),
        ),
    ]
