# Generated by Django 5.1.4 on 2024-12-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_uuidtaggeditem_alter_therapist_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'verbose_name': 'セラピスト', 'verbose_name_plural': 'セラピスト一覧'},
        ),
    ]
