# Generated by Django 5.1.4 on 2024-12-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girl', models.CharField(choices=[('girl1', '女の子1'), ('girl2', '女の子2'), ('girl3', '女の子3')], max_length=50, verbose_name='女の子')),
                ('customer_name', models.CharField(max_length=100, verbose_name='お客様のお名前')),
                ('visit_date', models.DateField(verbose_name='ご来店日')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
