# Generated by Django 4.2.20 on 2025-04-23 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '__first__'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '口コミ', 'verbose_name_plural': '口コミ一覧'},
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='review',
            name='girl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.therapist', verbose_name='女の子'),
        ),
    ]
