# Generated by Django 5.1.4 on 2024-12-27 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_uuidtaggeditem_alter_therapist_tags'),
        ('review', '0002_alter_review_girl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='girl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list.therapist'),
        ),
    ]
