# Generated by Django 5.1.4 on 2024-12-18 02:49

import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('age', models.PositiveIntegerField(verbose_name='年齢')),
                ('height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='身長（cm）')),
                ('bust', models.CharField(max_length=10, verbose_name='バスト')),
                ('waist', models.CharField(max_length=10, verbose_name='ウエスト')),
                ('hip', models.CharField(max_length=10, verbose_name='ヒップ')),
                ('joining_date', models.DateField(verbose_name='入店日')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='therapist_photos/', verbose_name='写真')),
                ('schedule', models.JSONField(blank=True, null=True, verbose_name='出勤予定')),
                ('video', models.FileField(blank=True, null=True, upload_to='therapist_videos/', verbose_name='動画')),
                ('x_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='xリンク')),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagramリンク')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
        ),
    ]
