# Generated by Django 5.1.4 on 2024-12-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_therapist_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='status',
            field=models.CharField(choices=[('available', '予約受付中'), ('full', '満員御礼')], default='available', max_length=10, verbose_name='予約状況'),
        ),
    ]
